ERROR - 2024-09-30 11:49:05 --> mysqli_sql_exception: MySQL server has gone away in D:\xampp\htdocs\debitnote\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\xampp\htdocs\debitnote\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 D:\xampp\htdocs\debitnote\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 D:\xampp\htdocs\debitnote\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 D:\xampp\htdocs\debitnote\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\debitnote\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\debitnote\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\debitnote\app\Controllers\Login.php(26): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\debitnote\system\CodeIgniter.php(902): App\Controllers\Login->index()
#8 D:\xampp\htdocs\debitnote\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 D:\xampp\htdocs\debitnote\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\debitnote\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-09-30 11:49:05 --> MySQL server has gone away
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `userdata`
WHERE `username` = \'eng\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `userdata`
WHERE `username` = \'eng\'')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `userdata`
WHERE `username` = \'eng\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `userdata`
WHERE `username` = :username:', [...], false)
 5 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Login.php(26): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Login->index()
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-09-30 11:54:56 --> Uncaught ValueError: realpath(): Argument #1 ($path) must not contain any null bytes in D:\xampp\htdocs\debitnote\system\Common.php:90
Stack trace:
#0 D:\xampp\htdocs\debitnote\system\Common.php(90): realpath('%PDF-1.7\n1 0 ob...')
#1 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(483): clean_path('%PDF-1.7\n1 0 ob...')
#2 [internal function]: CodeIgniter\Debug\Exceptions::CodeIgniter\Debug\{closure}('%PDF-1.7\n1 0 ob...')
#3 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(488): array_map(Object(Closure), Array)
#4 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(114): CodeIgniter\Debug\Exceptions::renderBacktrace(Array)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#6 {main}
  thrown
in SYSTEMPATH\Common.php on line 90.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-09-30 11:56:01 --> Uncaught ValueError: realpath(): Argument #1 ($path) must not contain any null bytes in D:\xampp\htdocs\debitnote\system\Common.php:90
Stack trace:
#0 D:\xampp\htdocs\debitnote\system\Common.php(90): realpath('%PDF-1.7\n1 0 ob...')
#1 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(483): clean_path('%PDF-1.7\n1 0 ob...')
#2 [internal function]: CodeIgniter\Debug\Exceptions::CodeIgniter\Debug\{closure}('%PDF-1.7\n1 0 ob...')
#3 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(488): array_map(Object(Closure), Array)
#4 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(114): CodeIgniter\Debug\Exceptions::renderBacktrace(Array)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#6 {main}
  thrown
in SYSTEMPATH\Common.php on line 90.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-09-30 11:56:23 --> Uncaught ValueError: realpath(): Argument #1 ($path) must not contain any null bytes in D:\xampp\htdocs\debitnote\system\Common.php:90
Stack trace:
#0 D:\xampp\htdocs\debitnote\system\Common.php(90): realpath('%PDF-1.7\n1 0 ob...')
#1 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(483): clean_path('%PDF-1.7\n1 0 ob...')
#2 [internal function]: CodeIgniter\Debug\Exceptions::CodeIgniter\Debug\{closure}('%PDF-1.7\n1 0 ob...')
#3 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(488): array_map(Object(Closure), Array)
#4 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(114): CodeIgniter\Debug\Exceptions::renderBacktrace(Array)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#6 {main}
  thrown
in SYSTEMPATH\Common.php on line 90.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-09-30 11:56:23 --> Uncaught ValueError: realpath(): Argument #1 ($path) must not contain any null bytes in D:\xampp\htdocs\debitnote\system\Common.php:90
Stack trace:
#0 D:\xampp\htdocs\debitnote\system\Common.php(90): realpath('%PDF-1.7\n1 0 ob...')
#1 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(483): clean_path('%PDF-1.7\n1 0 ob...')
#2 [internal function]: CodeIgniter\Debug\Exceptions::CodeIgniter\Debug\{closure}('%PDF-1.7\n1 0 ob...')
#3 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(488): array_map(Object(Closure), Array)
#4 D:\xampp\htdocs\debitnote\system\Debug\Exceptions.php(114): CodeIgniter\Debug\Exceptions::renderBacktrace(Array)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#6 {main}
  thrown
in SYSTEMPATH\Common.php on line 90.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
